src/Entity/Movie.php
<?php

namespace App\Entity;

use App\Repository\MovieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MovieRepository::class)]
class Movie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 4, max: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank]
    #[Assert\Type(\DateTimeInterface::class)]
    private ?\DateTimeInterface $release_date = null;

    #[ORM\OneToMany(mappedBy: 'movie', targetEntity: Quote::class)]
    private Collection $quotes;

    #[ORM\Column(nullable: true)]
    #[Assert\NotBlank]
    #[Assert\Type('float')]
    private ?float $Rating = null;

    public function __construct()
    {
        $this->quotes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(\DateTimeInterface $release_date): self
    {
        $this->release_date = $release_date;

        return $this;
    }

    /**
     * @return Collection<int, Quote>
     */
    public function getQuotes(): Collection
    {
        return $this->quotes;
    }

    public function addQuote(Quote $quote): self
    {
        if (!$this->quotes->contains($quote)) {
            $this->quotes->add($quote);
            $quote->setMovie($this);
        }

        return $this;
    }

    public function removeQuote(Quote $quote): self
    {
        if ($this->quotes->removeElement($quote)) {
            // set the owning side to null (unless already changed)
            if ($quote->getMovie() === $this) {
                $quote->setMovie(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->name;
    }

    public function getRating(): ?float
    {
        return $this->Rating;
    }

    public function setRating(?float $Rating): self
    {
        $this->Rating = $Rating;

        return $this;
    }
}

src/Entity/Quote.php
<?php

namespace App\Entity;

use App\Repository\QuoteRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: QuoteRepository::class)]
class Quote
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 3, max: 255)]
    private ?string $quote = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 3, max: 255)]
    private ?string $character_name = null;

    #[ORM\ManyToOne(inversedBy: 'quotes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Movie $movie = null;

    #[Assert\Type(type: 'integer')]
    #[Assert\Range(min: 1, max: 100)]
    #[ORM\Column(type: 'integer', nullable: true)]
    private ?int $times_said = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $magic_string = null;

    #[Assert\IsTrue(message: "Each character in the magic string must appear exactly twice")]
        private function hasOnlyDoubleChars(): bool
        {
            $charCount = count_chars($this->magic_string, 1);
            foreach ($charCount as $char => $count) {
                if ($count !== 2) {
                    return false;
                }
            }
            return true;
        }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuote(): ?string
    {
        return $this->quote;
    }

    public function setQuote(string $quote): self
    {
        $this->quote = $quote;

        return $this;
    }

    public function getCharacterName(): ?string
    {
        return $this->character_name;
    }

    public function setCharacterName(string $character_name): self
    {
        $this->character_name = $character_name;

        return $this;
    }

    public function getMovie(): ?Movie
    {
        return $this->movie;
    }

    public function setMovie(?Movie $movie): self
    {
        $this->movie = $movie;

        return $this;
    }

    public function getTimesSaid(): ?int
    {
        return $this->times_said;
    }

    public function setTimesSaid(?int $times_said): self
    {
        $this->times_said = $times_said;

        return $this;
    }

    public function getMagicString(): ?string
    {
        return $this->magic_string;
    }

    public function setMagicString(?string $magic_string): self
    {
        $this->magic_string = $magic_string;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getQuote();
    }
}

src/Form/QuoteType.php
<?php

namespace App\Form;

use App\Entity\Quote;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuoteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('quote')
            ->add('character_name')
            ->add('movie')
            ->add('times_said')
            ->add('magic_string');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Quote::class,
        ]);
    }
}

src/Controller/QuoteController.php
<?php

namespace App\Controller;

use App\Entity\Quote;
use App\Form\QuoteType;
use App\Repository\QuoteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/quotes')]
class QuoteController extends AbstractController
{

    #[Route('/', name: 'app_quote_index', methods: ['GET'])]
    public function index(Request $request, QuoteRepository $quoteRepository): Response
    {
        $quotes = $quoteRepository->findAll();

        return $this->render('quote/index.html.twig', [
            'quotes' => $quotes,
        ]);
    }

    #[Route('/search', name: 'app_quote_search', methods: ['GET'])]
    public function search(Request $request, QuoteRepository $quoteRepository): Response
    {

        $query = $request->query->get('query');
        if (empty($query)) {
            return $this->redirectToRoute('app_quote_index');
        }
        $quotes = $quoteRepository->findAllByQuery($query);

        return $this->render('quote/index.html.twig', [
            'quotes' => $quotes,
        ]);
    }

    #[Route('/new', name: 'app_quote_new', methods: ['GET', 'POST'])]
    public function new(Request $request, QuoteRepository $quoteRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $quote = new Quote();
        $form = $this->createForm(QuoteType::class, $quote);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $quoteRepository->save($quote, true);

            return $this->redirectToRoute('app_quote_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('quote/new.html.twig', [
            'quote' => $quote,
            'form' => $form,
        ]);
    }

    #[Route('/random', name: 'app_quote_random', methods: ['GET'])]
    public function random(Request $request, QuoteRepository $quoteRepository): Response
    {
        $quote = $quoteRepository->getRandomQuote();

        return $this->render('quote/index.html.twig', [
            'quotes' => [$quote],
        ]);
    }

    #[Route('/{id}', name: 'app_quote_show', methods: ['GET'])]
    public function show(Quote $quote): Response
    {
        return $this->render('quote/show.html.twig', [
            'quote' => $quote,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_quote_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Quote $quote, QuoteRepository $quoteRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        $form = $this->createForm(QuoteType::class, $quote);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $quoteRepository->save($quote, true);

            return $this->redirectToRoute('app_quote_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('quote/edit.html.twig', [
            'quote' => $quote,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_quote_delete', methods: ['POST'])]
    public function delete(Request $request, Quote $quote, QuoteRepository $quoteRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        if ($this->isCsrfTokenValid('delete' . $quote->getId(), $request->request->get('_token'))) {
            $quoteRepository->remove($quote, true);
        }

        return $this->redirectToRoute('app_quote_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/quote/_delete_form.html.twig
<form method="post" action="{{ path('app_quote_delete', {'id': quote.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ quote.id) }}">
    <button class="btn">Delete</button>
</form>

templates/quote/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/quote/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Quote{% endblock %}

{% block body %}
    <h1>Edit Quote</h1>

    {{ include('quote/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_quote_index') }}">back to list</a>

    {{ include('quote/_delete_form.html.twig') }}
{% endblock %}

templates/quote/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quote index{% endblock %}

{% block body %}
    <h1>Quote index</h1>
    {# create a searchbar #}
    <form action="{{ path('app_quote_search') }}" method="get">
        <input type="text" name="query" placeholder="Search">
        <button type="submit">Search</button>
    </form>
    <a href="{{ path('app_quote_random') }}">Random quote</a>
    <table class="table">
        <thead>
        <tr>
            <th>Movie Name</th>
            <th>Release year</th>
            <th>Quote</th>
            <th>Character_name</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for quote in quotes %}
            <tr>
                <td>{{ quote.movie.name }}</td>
                <td>{{ quote.movie.releaseDate ? quote.movie.releaseDate|date('Y-m-d') : '' }}</td>
                <td>{{ quote.quote }}</td>
                <td>{{ quote.characterName }}</td>
                <td style="display: flex; flex-direction: row; gap: 5px;">
                    <a href="{{ path('app_quote_show', {'id': quote.id}) }}">show</a>
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('app_quote_edit', {'id': quote.id}) }}">edit</a>
                        {{ include('quote/_delete_form.html.twig') }}
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('app_quote_new') }}">Create new</a>
        <br>
        <a href="{{ path('app_movie_new', { redirect: 'app_quote_index'}) }}">Create new Movie</a>
        <br>
    {% endif %}
    <a href="{{ path('app_movie_index') }}">Movie list</a>
{% endblock %}

templates/quote/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Quote{% endblock %}

{% block body %}
    <h1>Create new Quote</h1>

    {{ include('quote/_form.html.twig') }}

    <a href="{{ path('app_movie_new', { redirect: 'app_quote_new'}) }}">Create new Movie</a>

    <a href="{{ path('app_quote_index') }}">back to list</a>
{% endblock %}

templates/quote/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quote{% endblock %}

{% block body %}
    <h1>Quote</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Movie</th>
                <td>{{ quote.movie.name }}</td>
            </tr>
            <tr>
                <th>Quote</th>
                <td>{{ quote.quote }}</td>
            </tr>
            <tr>
                <th>Character_name</th>
                <td>{{ quote.characterName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_quote_index') }}">back to list</a>

    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('app_quote_edit', {'id': quote.id}) }}">edit</a>
    {% endif %}

    {{ include('quote/_delete_form.html.twig') }}
{% endblock %}